### ISSUE TITLE
Does not work on macOS 10.15.2

### ISSUE THREAD

**Issue by xuoutput** [round/CatchMouse#6]

**Comment by wijnanb** [comment]
You will need to grant Accessibility permissions for this app.

System Preferences > Security & Privacy > Accessibility

**Comment by xuoutput** [comment]
Still not working @wijnanb 
![image](https://user-images.githubusercontent.com/16385443/84637115-eb085a80-af27-11ea-91cf-27539c708fcf.png)

**Comment by donote** [comment]
mac10.15 not available, the cursor can be displayed but not focused

**Comment by HoweChen** [comment]
@xuoutput @donote 

Just quit the catch mouse app, 
click the minus button to remove the app from the accessibility list,
re-add it to the list

The cursor is focused again for me on the latest OS.

**Comment by djkgamc** [comment]
omg thanks @HoweChen
